<?php
/**
 * TL_ROOT/system/modules/tabcontrol/languages/cs/tl_content.php 
 * 
 * Contao extension: tabcontrol 3.0.1 
 * Czech translation file 
 * 
 * Copyright : © 2011-2014 Christian Barkowsky 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christian Barkowsky Webentwicklung (christian.barkowsky), http://christianbarkowsky.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['tabcontrol']['0'] = "TabControl záložky";
$GLOBALS['TL_LANG']['CTE']['tabcontrol']['1'] = "Vytvořit nový obsahový prvek se záložkami.";
$GLOBALS['TL_LANG']['tl_content']['tabBehaviour']['0'] = "Chování záložek";
$GLOBALS['TL_LANG']['tl_content']['tabBehaviour']['1'] = "Prosím vyberte, jak se má přepínat mezi jednotlivými záložkami.";
$GLOBALS['TL_LANG']['tl_content']['tabClasses']['0'] = "Kaskádové styly";
$GLOBALS['TL_LANG']['tl_content']['tabClasses']['1'] = "Ponechte pole prázdné pro použítí standardních tříd stylů, nebo zadejte vlastní třídy stylů.";
$GLOBALS['TL_LANG']['tl_content']['tabTitles']['0'] = "Hlavičky záložek";
$GLOBALS['TL_LANG']['tl_content']['tabTitles']['1'] = "Uveďte prosím název záložek. HTML tagy jsou povoleny.";
$GLOBALS['TL_LANG']['tl_content']['tabType']['0'] = "Provozní režim";
$GLOBALS['TL_LANG']['tl_content']['tabType']['1'] = "Prosím, zvolte provozní režim prvku záložek.";
$GLOBALS['TL_LANG']['tl_content']['tab_legend'] = "Záložky nastavení";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['click']['0'] = "Kliknutím";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['click']['1'] = "Při kliknutí na hlavičku záložky se odpovídající obsah stává viditelným.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['mouseover']['0'] = "Přejetím";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['mouseover']['1'] = "Při přejetí ukazatele myši přes hlavičku záložky se odpovídající obsah stává viditelným.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstart']['0'] = "Start obsahu záložky";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstart']['1'] = "Znamená začátek obsahu nové záložky, která zahrnuje několik prvků obsahu.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstop']['0'] = "Konec obsahu záložky";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstop']['1'] = "Znamená konec obsahu nové záložky, která zahrnuje několik prvků obsahu.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontroltab']['0'] = "Hlavička záložek";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontroltab']['1'] = "Vytvoří novou skupinu záložek.";
 
?>
