<?php
/**
 * TL_ROOT/system/modules/tabcontrol/languages/de/tl_content.php 
 * 
 * Contao extension: tabcontrol 1.1.4 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2009-2011 by Jean-Bernard Valentaten 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Jean-Bernard Valentaten (Brains) 
 * Translator: Jean-Bernard Valentaten (Brains) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['tabcontrol']['0'] = "Reiter";
$GLOBALS['TL_LANG']['CTE']['tabcontrol']['1'] = "erzeugt ein neues Reiterelement";
$GLOBALS['TL_LANG']['tl_content']['tabBehaviour']['0'] = "Verhaltensweise";
$GLOBALS['TL_LANG']['tl_content']['tabBehaviour']['1'] = "Stellen Sie hier ein auf welches Ereignis die Reiter reagieren sollen.";
$GLOBALS['TL_LANG']['tl_content']['tabClasses']['0'] = "Klassennamen";
$GLOBALS['TL_LANG']['tl_content']['tabClasses']['1'] = "Lassen Sie das Feld leer, um die Standard-Klassennamen zu verwenden, oder geben Sie eigene Reiter- und Panelklassen ein.";
$GLOBALS['TL_LANG']['tl_content']['tabTitles']['0'] = "Reiterüberschriften";
$GLOBALS['TL_LANG']['tl_content']['tabTitles']['1'] = "Bitte geben Sie die Überschriften der Reiter an. HTML-Tags sind erlaubt.";
$GLOBALS['TL_LANG']['tl_content']['tabType']['0'] = "Betriebsart";
$GLOBALS['TL_LANG']['tl_content']['tabType']['1'] = "Bitte wählen Sie die Betriebsart des Reiterelements.";
$GLOBALS['TL_LANG']['tl_content']['tab_legend'] = "Reitereinstellungen";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['click']['0'] = "Anklicken";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['click']['1'] = "Beim Anklicken eines Reiters wird das zugehörige Panel sichtbar.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['mouseover']['0'] = "Berühren";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['mouseover']['1'] = "Beim Berühren eines Reiters mit dem Mauszeiger wird das zugehörige Panel sichtbar.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstart']['0'] = "Panel Anfang";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstart']['1'] = "Markiert den Anfang eines neuen Panels, das mehrere Inhaltselement umfasst.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstop']['0'] = "Panel Ende";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstop']['1'] = "Markiert das Ende eines Panel, das mehrere Inhaltselemente umfasst.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontroltab']['0'] = "Reitergruppe";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontroltab']['1'] = "Erzeugt eine neue Gruppe von Reitern.";
 
?>
