services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Plenta\TabControl\:
        resource: ../src/*

    Plenta\TabControl\Controller\Contao\ContentElement\TabControlController:
        public: true