<?php
/**
 * TL_ROOT/system/modules/tabcontrol/languages/ru/tl_content.php 
 * 
 * Contao extension: tabcontrol 1.1.4 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; 2009-2011 by Jean-Bernard Valentaten 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Jean-Bernard Valentaten (Brains) 
 * Translator: Eugene Rybyakov (evgenioni), contaotraining.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['tabcontrol']['0'] = "Вкладки";
$GLOBALS['TL_LANG']['CTE']['tabcontrol']['1'] = "Создать новый набор вкладок";
$GLOBALS['TL_LANG']['tl_content']['tabBehaviour']['0'] = "Реакция";
$GLOBALS['TL_LANG']['tl_content']['tabBehaviour']['1'] = "Выберите поведение вкладок на щелчок или перемещение.";
$GLOBALS['TL_LANG']['tl_content']['tabClasses']['0'] = "Названия классов вкладок и панелей";
$GLOBALS['TL_LANG']['tl_content']['tabClasses']['1'] = "Оставьте поля пустыми, чтобы использовать системные настройки, либо задайте специальные названия классов для блока вкладок и для переключаемых панелей.";
$GLOBALS['TL_LANG']['tl_content']['tabTitles']['0'] = "Названия вкладок";
$GLOBALS['TL_LANG']['tl_content']['tabTitles']['1'] = "Задайте названия вкладок. Разрешены HTML-теги.";
$GLOBALS['TL_LANG']['tl_content']['tabType']['0'] = "Управляющие метки";
$GLOBALS['TL_LANG']['tl_content']['tabType']['1'] = "Выберите управляющую метку для организации вкладок на странице. Обычно, сначала формируют \"Группу вкладок\" с названиями, а затем вставляют управляющие теги \"Начало...\" и \"Конец группы вкладок\", между которыми вы можете расположить нужный контент.";
$GLOBALS['TL_LANG']['tl_content']['tab_legend'] = "Настройки Вкладок";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['click']['0'] = "Щелчок";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['click']['1'] = "Вкладки переключаются по щелчку на них.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['mouseover']['0'] = "Перемещение";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['mouseover']['1'] = "Вкладки переключаются, когда курсор мыши перемещается над ними.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstart']['0'] = "Начало группы вкладок";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstart']['1'] = "Метка начала блока переключаемых панелей различного контента.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstop']['0'] = "Конец группы вкладок";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontrolstop']['1'] = "Метка конца блока переключаемых панелей различного контента.";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontroltab']['0'] = "Группа вкладок";
$GLOBALS['TL_LANG']['tl_content']['tabControl']['tabcontroltab']['1'] = "Создает новую группу вкладок.";
 
?>
